version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: viva-rfc
    container_name: viva-rfc
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules: